long int power(int b, int e);
unsigned long int prefix_sum(unsigned int n);
unsigned long int suffix_sum(unsigned int n, unsigned int s);
unsigned int sum_digits(unsigned int num);
int find_min(int* arr, int n);
int len(char* S);
int v_sorted(const char *A);
unsigned int reverse_words(char *str, unsigned int idx);
void reverse(char *str, unsigned int len);
int binary_search(const int *A, unsigned int n, int k);
int order(const int *A, unsigned int n);
